Added carousel component
ReinisZogots/renome-react-ts pull request #4
Opened 2022-03-01 11:04 UTC by ReinisZogots

2022-03-01 12:30 UTC, YuraLeo94 requested changes

2022-03-01 12:30 UTC, YuraLeo94 commented on src/components/atoms/CarouselSlideButton/index.tsx
> +      }
Not sure what you need tenar statement here. For each image, you have only different `name`(`arrow-right` and `arrow-left`) and `alt`, so feel free to send them as props and use.

2022-03-01 13:41 UTC, ilze-dom approved these changes

2022-03-02 07:25 UTC, Jalal999 commented on src/components/atoms/CarouselSlideButton/index.tsx
> +      }
you can also bring these imgs from atoms

2022-03-02 07:35 UTC, Jalal999 approved these changes

2022-03-07 07:31 UTC, YuraLeo94 approved these changes

2022-03-07 07:33 UTC, merged