Added navigation component
ReinisZogots/renome-react-ts pull request #5
Opened 2022-03-18 09:52 UTC by ReinisZogots

2022-03-18 13:16 UTC, Jose-Hash-Dev approved these changes

2022-03-21 07:47 UTC, VSlobolinskyi requested changes

2022-03-21 07:47 UTC, VSlobolinskyi commented on src/components/molecules/navigationMenu/index.tsx
> +const Menu: React.FC<MenuProps> = ({ toggleSubMenu, setIsMenuOpen}) => {
Also if you are not spreading props you can go with just `const Menu = (props: MenuProps) => {}` but this is not something you should implement but rather a good to know thing

2022-03-21 07:47 UTC, VSlobolinskyi commented on src/structure.json
> +  "navigationIcons": {
Please make a nested structure where you for example would have: 
`
"shoppingCart": {
    "altTag": "..."
    "path": "..."
}
`

2022-03-21 08:32 UTC, VSlobolinskyi approved these changes

2022-03-21 08:49 UTC, Jalal999 commented on src/components/molecules/shoppingCart/index.tsx
> +interface CartProps{
space

2022-03-21 08:49 UTC, Jalal999 commented on src/components/molecules/shoppingCart/index.tsx
> +      if(cartRef.current && !cartRef.current.contains(event.target as Node)){
space

2022-03-21 08:50 UTC, Jalal999 commented on src/components/molecules/shoppingCart/index.tsx
> +    const handler = (event: Event) =>{
space

2022-03-21 08:51 UTC, Jalal999 approved these changes

2022-03-22 11:11 UTC, merged